keywords: R,Python,数据科学,可视化
author: Ben Wong,wenbinben@gmail.com
description: Nothing lasts forever.
avatar: https://secure.gravatar.com/avatar/e71df8021446fe9759a9928b1dd5c28d?s=180&r=G&d=

twitter: Ben_wenbin
rss: atom.xml
weibo: ben0036
instagram: hwbinbenben

# Comment
duoshuo: yalei
disqus:
